# Generated by Django 2.0 on 2020-06-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
